#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
LiDAR FUSION CloudMetrics & GridMetrics Batch Generator
------------------------------------------------------
Scans a folder of LiDAR `.las` point cloud files and generates a Windows Batch (`.bat`)
file to calculate forest structure metrics (canopy cover, height percentiles p95/p90, 
point densities, etc.) using USDA Forest Service FUSION Command Line utilities.

FUSION CLI utilities targeted:
- CloudMetrics: Calculates stats for the entire point cloud.
- GridMetrics: Generates rasterized grid metrics (e.g. canopy cover at 30m resolution).

Usage:
    python fusion_cloudmetrics_generator.py --folder C:/data/las --out_bat run_metrics.bat
"""

import os
import argparse

def generate_bat_script(las_folder, output_bat_path, fusion_dir, min_height, grid_cell_size):
    """Generates a batch file containing commands to run CloudMetrics and GridMetrics on all .las files."""
    try:
        # Check if directory exists
        if not os.path.isdir(las_folder):
            print(f"Error: Target LAS folder '{las_folder}' does not exist.")
            return False
            
        las_files = [f for f in os.listdir(las_folder) if f.lower().endswith(".las")]
        if not las_files:
            print(f"Warning: No .las files found in '{las_folder}'.")
            
        # Ensure FUSION paths terminate with backslash if provided
        if fusion_dir and not fusion_dir.endswith(("\\", "/")):
            fusion_dir += "\\"
            
        with open(output_bat_path, "w") as bat:
            bat.write("@echo off\n")
            bat.write("REM ========================================================================\n")
            bat.write("REM Batch LiDAR Metrics Calculation using USDA Forest Service FUSION CLI\n")
            bat.write("REM Generated by FUSION CloudMetrics Generator script\n")
            bat.write("REM ========================================================================\n\n")
            
            # Setup folders
            bat.write("REM Create output directories\n")
            bat.write(f"mkdir \"{las_folder}\\metrics\" 2>nul\n")
            bat.write(f"mkdir \"{las_folder}\\grids\" 2>nul\n\n")
            
            # Iterate through files
            for las in sorted(las_files):
                base_name = os.path.splitext(las)[0]
                las_path = os.path.join(las_folder, las).replace("/", "\\")
                
                # Output paths
                cloud_csv = os.path.join(las_folder, "metrics", f"{base_name}_cloud_stats.csv").replace("/", "\\")
                grid_csv = os.path.join(las_folder, "grids", f"{base_name}_grid_metrics").replace("/", "\\") # FUSION appends .csv
                
                bat.write(f"echo Processing metrics for {las}...\n")
                
                # 1. CloudMetrics call
                # Syntax: CloudMetrics /min:height_break input_las output_csv
                cloud_cmd = f"\"{fusion_dir}CloudMetrics.exe\" /min:{min_height} /above:{min_height} \"{las_path}\" \"{cloud_csv}\""
                bat.write(f"{cloud_cmd}\n")
                
                # 2. GridMetrics call
                # Syntax: GridMetrics /min:height_break grid_cell_size height_break output_csv input_las
                grid_cmd = f"\"{fusion_dir}GridMetrics.exe\" /min:{min_height} {grid_cell_size} {min_height} \"{grid_csv}\" \"{las_path}\""
                bat.write(f"{grid_cmd}\n\n")
                
            bat.write("echo ========================================================================\n")
            bat.write("echo FUSION batch processing complete!\n")
            bat.write("echo ========================================================================\n")
            bat.write("pause\n")
            
        print(f"Success: Batch file created successfully at '{output_bat_path}'")
        print(f"Total .las files cataloged: {len(las_files)}")
        return True
        
    except Exception as e:
        print(f"Error writing batch file: {e}")
        return False

def main():
    parser = argparse.ArgumentParser(description="LiDAR FUSION CloudMetrics & GridMetrics Batch Generator")
    parser.add_argument("--folder", required=True, help="Path to directory containing input .las files.")
    parser.add_argument("--out_bat", required=True, help="Full path of the Windows .bat script to generate.")
    parser.add_argument("--fusion_path", default="C:\\Program Files\\FUSION", 
                        help="Path to FUSION installation directory (default: C:\\Program Files\\FUSION).")
    parser.add_argument("--min_height", type=float, default=2.0, 
                        help="Height cutoff/break in meters (default: 2.0 to ignore ground and understory).")
    parser.add_argument("--cell_size", type=int, default=30, 
                        help="Spatial resolution of GridMetrics output cells in meters (default: 30).")
    
    args = parser.parse_args()
    generate_bat_script(args.folder, args.out_bat, args.fusion_path, args.min_height, args.cell_size)

if __name__ == "__main__":
    main()
