# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# domain_buffer_clip.py
# Created on: 2017-02-22 10:03:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("3D")


# Local variables:
v1008_1_tif = "C:\\Users\\adamclark\\Desktop\\deleteme\\1008_1.tif"
v1008_1_domain_py_shp = "C:\\Users\\adamclark\\Desktop\\deleteme\\1008_1_domain_py.shp"
v1008_1_domain_300buf_py_shp = "C:\\Users\\adamclark\\Desktop\\deleteme\\1008_1_domain_300buf_py.shp"
v1008_1_clip_tif = "C:\\Users\\adamclark\\Desktop\\deleteme\\1008_1_clip.tif"

### Process: Raster Domain
##arcpy.RasterDomain_3d(v1008_1_tif, v1008_1_domain_py_shp, "POLYGON")
##
### Process: Buffer
##arcpy.Buffer_analysis(v1008_1_domain_py_shp, v1008_1_domain_300buf_py_shp, "-300 Meters", "FULL", "ROUND", "NONE", "")
desc      = arcpy.Describe(v1008_1_domain_300buf_py_shp)
ExtObj    = desc.extent
clip      = "%d %d %d %d" % (ExtObj.XMin, ExtObj.YMin, ExtObj.XMax, ExtObj.YMax)
# Process: Clip
arcpy.Clip_management(v1008_1_tif, clip, v1008_1_clip_tif, v1008_1_domain_300buf_py_shp, "256", "ClippingGeometry")

