# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# exportClip.py
# Created on: 2017-02-21 13:51:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
v1008_1_tif = "1008_1.tif"
v1008_1_domain_300buf = "1008_1_domain_300buf"
v1008_1_300_trim1_img = "C:\\Users\\adamclark\\Desktop\\deleteme\\1008_1_300_trim1.img"

# Process: Clip
arcpy.Clip_management(v1008_1_tif, "530369.146738607 3803380.77309221 533712.737557564 3806720.04767776", v1008_1_300_trim1_img, v1008_1_domain_300buf, "256", "ClippingGeometry")

